### ISSUE TITLE
cache.py:retrieve_local_file_info:'file' variable not defined.

### ISSUE THREAD

**Issue by adrinjalali** [Sage-Bionetworks/synapsePythonClient#151]
In `cache.py`, function `retrieve_local_file_info` has `if file not None` as a part of the condition. `file` is a function is python2 and is not None, but it's removed in python3, and I guess the coder didn't mean to check if the function `file` exists here. Should it be removed from the `if` clause?

**Comment by larssono** [comment]
Fixed by latest cache refactor
