### ISSUE TITLE
Certificate has no subjectAltName, falling back to check for a commonName for now

### ISSUE THREAD

**Issue by ags-wsu** [Sage-Bionetworks/synapsePythonClient#342]
Upgrading to synapseclient 1.6.1, I am now getting the following warning multiple times:

``/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for file-prod.prod.sagebase.org has no  `subjectAltName` , falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)``

**Comment by kdaily** [comment]
What verson of `urllib3` are you using? I have `1.15.1` with no problems.

**Comment by ags-wsu** [comment]
I've upgraded the following packages and it has seemed to fix this problem:

Successfully installed cffi-1.9.1 cryptography-1.7.1 idna-2.1 ipaddress-1.0.17 pycparser-2.17 setuptools-32.0.0 requests-2.12.4

**Comment by kdaily** [comment]
Thank you for the feedback! I'll close for now, please reopen if you run into related issues.
