### ISSUE TITLE
Developer interested in helping our project

### ISSUE THREAD

**Issue by wildaces215** [Sage-Bionetworks/synapsePythonClient#378]
Hello I am a college student that is interested in helping the project. I have found this project off the mozilla website where do I start to help improve the project itself?

**Comment by kdaily** [comment]
Hello! We currently host issues for this in Jira. You can see a list of open issues here:

https://sagebionetworks.jira.com/projects/SYNPY/issues

**Comment by wildaces215** [comment]
Ok understood thank you!

**Comment by meredithslota** [comment]
Hi @wildaces215 -- excited that you want to help out here. We just released version 1.7 of the client and are starting work on 1.8. You can filter that project that @kdaily linked to by fixVersion = py-1.8 to check it out. 

As @kdaily mentioned, we haven't done a ton of outreach yet to the developer community and as such are kind of figuring out how best to engage with folks like you who want to help. Is there anything in particular you are interested in helping with? Happy to follow-up outside of this issue, which I'm going to go ahead and close out now.
