### ISSUE TITLE
How to list a folder?

### ISSUE THREAD

**Issue by buchanae** [Sage-Bionetworks/synapsePythonClient#389]
I'm not sure how to list a folder. Am I missing something obvious? Seems like along with get/store, list is one of the most important file system actions.

I dug into the code and found _list(), but it's too complicated for me to understand.

**Comment by zimingd** [comment]
You can use either the synapse id or the object retrieved from a syn.get() as an argument to _list().
Here is an example:

```
import synapseclient
syn = synapseclient.login("username", "password")
folder_entity = syn.get("syn123") # suppose syn123 was the id of a folder

# you can either do 
syn._list("syn123")
# or do
syn._list(folder_entity)

# use resursive=True to recursively print nested folders
syn._list("syn123", recursive=True)
# once again you can also do
syn._list(folder_entity, recursive=True)
```

I'm not really sure why there is not a documented public method that uses _list. I'll file an issue for that on JIRA.

**Comment by kdaily** [comment]
@zimingd looks like the current implementation of `_list` uses the entity query service. It should use the [`/entity/children`](http://docs.synapse.org/rest/POST/entity/children.html) REST endpoint.

@buchanae - the `synapseutils` module also has the [`walk` method](https://github.com/Sage-Bionetworks/synapsePythonClient/blob/6255001dbf22bc3ef70a8e021c6d6ead3a33a9d5/synapseutils/walk.py#L5-L24). This needs more documentation as well!
