### ISSUE TITLE
1.7.4 fails to install

### ISSUE THREAD

**Issue by mmerickel** [Sage-Bionetworks/synapsePythonClient#507]
1.7.4 is failing to install into my CI environment, however 1.7.3 works fine. It looks related to https://github.com/Sage-Bionetworks/synapsePythonClient/commit/923c141677197fe7fd48508832041c06d72c7ed8#diff-2eeaed663bd0d25b7e608891384b7298

```
$ env/bin/pip install synapseclient==1.7.4
    <snip>
    running install_data
    error: can't copy '.synapseConfig': doesn't exist or not a regular file
```

**Comment by zimingd** [comment]
This was fixed in 1.7.5 and 1.7.4 has been removed from PyPI
