### ISSUE TITLE
Have an exclusion/inclusion list for syncFromSynapse (feature request)

### ISSUE THREAD

**Issue by npklein** [Sage-Bionetworks/synapsePythonClient#525]
Apologies if this is already possible, but I could not find it in the documentation.   

When using syncFromSynapse() you can not exclude files from download. For example, I do not want to download the *.bam files. It would be great if there was a parameter for syncFromSynapse() with an exclude (or include) list of files.

**Comment by zimingd** [comment]
Thank you for submitting this feature request. We track issues on JIRA so I have created a JIRA issue on your behalf (https://sagebionetworks.jira.com/browse/SYNPY-691). Progress updates for this feature will be posted there.

We are currently in the process of validating a new release so unfortunately this feature will not be released with the next version (1.8.0). I will try to complete this feature for the 1.8.1

**Comment by kdaily** [comment]
Hi @npklein,

This highlights a difference between `syncFromSynapse` and the `get` via a query. The former re-creates the folder hierarchy for you, while the latter downloads everything into the Synapse cache, or into a single directory that you specify. The reason that a `get` query doesn't (and probably shouldn't) recreate hierarchy is the file view table that is being queried can be constructed of any number of projects or individual folders. The resulting hierarchy could likely be very deep (many distinct nested folders), but very sparse (few files per folder).

@zimingd we probably *could* do that though for a `syn.get`, using http://docs.synapse.org/rest/GET/entity/id/path.html?

**Comment by npklein** [comment]
Thanks, will try it with the get query.

**Comment by jkiang13** [comment]
Closing per previous comments and closed corresponding JIRA issue. Please reopen if you feel this feature still needed and unresolved.
