### ISSUE TITLE
synapseutils.syncFromSynapse fails on empty folder

### ISSUE THREAD

**Issue by pcstout** [Sage-Bionetworks/synapsePythonClient#576]
`syncFromSynapse` throws `ValueError: The provided id: synMyFolderId is was neither a container nor a File` when it hits an empty folder.

Folder Structure:
```
-Folder-1
  -Folder-2
  -some-file.txt
```

`synapseutils.syncFromSynapse(syn, 'Folder-1-id')`

**Comment by kimyen** [comment]
Hello @pcstout,
Thank you for reporting the issue! It has been tracked here: https://sagebionetworks.jira.com/browse/SYNPY-688, fixed, and will be released soon. (Version 1.8.2)
