### ISSUE TITLE
Error when getting EntityViewSchema that does not exist

### ISSUE THREAD

**Issue by pcstout** [Sage-Bionetworks/synapsePythonClient#586]
Synapse Client 1.8.2

This request fails when the table doesn't exist.

`syn.get(EntityViewSchema(name='my_view', parent=my_project), downloadFile=False)`

Error:
```
File "synapseclient/client.py", line 626, in get
    self._check_entity_restrictions(bundle['restrictionInformation'], entity, kwargs.get('downloadFile', True))
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by kimyen** [comment]
Hi @pcstout 

Thank you for submitting a Github issue. Development work will be tracked here: https://sagebionetworks.jira.com/browse/SYNPY-805
