### ISSUE TITLE
os.errno removed in Python3.7

### ISSUE THREAD

**Issue by kellrott** [Sage-Bionetworks/synapsePythonClient#602]
In Python3.7 `os.errno` is removed. To make synapseclient library compatible, 
add `import errno` to `client.py` and change line https://github.com/Sage-Bionetworks/synapsePythonClient/blob/master/synapseclient/client.py#L1856 to 
```
            if exception.errno != errno.EEXIST:
```

**Comment by kimyen** [comment]
Thanks @kellrott !

We are currently not supporting Python version 3.7. But we plan to: https://sagebionetworks.jira.com/browse/SYNPY-802
