### ISSUE TITLE
Make CACHE_ROOT_DIR customizable

### ISSUE THREAD

**Issue by pcstout** [Sage-Bionetworks/synapsePythonClient#627]
On AWS Lambda you can only write to `/tmp`. We need a way to change the `CACHE_ROOT_DIR`.

My current workaround for this is:
```python
synapseclient.cache.CACHE_ROOT_DIR = os.path.join(tempfile.gettempdir(), 'synapseCache')
```

**Comment by kimyen** [comment]
@pcstout , the cache location is already configurable via our `.synapseConfig`: https://docs.synapse.org/articles/client_configuration.html
We may expose the ability to change the cache location using a python command in future release.
