### ISSUE TITLE
Re-uploads a file when there are no changes

### ISSUE THREAD

**Issue by pcstout** [Sage-Bionetworks/synapsePythonClient#674]
# Bug Report

## Operating system

Ubuntu Linux 18.04

## Client version

1.9.2

## Description of the problem

If a file already exists in a Project it will be uploaded even when the file has not changed. If you upload a second time it works as expected (it doesn't upload the file again). 

Repro. Steps:
- Create a new Project.
- Upload a file to the Project through the Synapse website.
- Do not make any changes to the local or remote file...
- Re-upload the file: `synapse add --parentid syn123456 test_file.txt` The file will be uploaded.

### Expected behavior

- The file will NOT be uploaded since it has not changed.

### Actual behavior

- The file is uploaded even though no change was made to it.

**Comment by kimyen** [comment]
@pcstout, thank you for reporting the issue!
Engineering work will be tracked here: https://sagebionetworks.jira.com/browse/SYNPY-946

**Comment by kdaily** [comment]
@pcstout ,

In the newest version of the client (v.19.4, https://github.com/Sage-Bionetworks/synapsePythonClient/releases/tag/v1.9.4) we added the option to pass `--noForceVersion` to the `synapse store` and `synapse add` subcommands, which will not bump the version if the file is not changed.

If this fixes this issue, please let me know so we can close this. Thanks!

**Comment by jkiang13** [comment]
Closing per previous response. If you feel this issue is still unresolved please reopen.
