### ISSUE TITLE
FileEntity 'path' property has wrong separator in Windows.

### ISSUE THREAD

**Issue by pcstout** [Sage-Bionetworks/synapsePythonClient#678]
# Bug Report

## Operating system

Windows 10 Pro

## Client version

1.9.2

## Description of the problem

On Windows (win32) the path separator in the FileEntity is wrong.

Repro. Steps:
- Upload a file and look at the returned object's `path` property.

### Expected behavior

- Path separator is `\` and the character casing is correct.
Correct path: `C:\\Users\\John\\AppData\\Local\\Temp\\tmpi7kpbq0s\\data\\core\\core_file_ace2.csv`

### Actual behavior

- Path separator is `/` and character casing is incorrect.
Incorrect path: `c:/users/john/appdata/local/temp/tmpi7kpbq0s/data/core/core_file_ace2.csv`

**Comment by kimyen** [comment]
Hello @pcstout ,

Thank you for reporting this issue. I notice that you put down `Ubuntu Linux 18.04` for Operating System. How do you run into problems with the Windows file path in a Linux environment?
Can you tell us more about how this problem impact your work? so that we can better prioritize this issue?

**Comment by pcstout** [comment]
@kimyen Sorry about that, it was on Windows 10 Pro. I updated the description.

**Comment by kimyen** [comment]
Thank you! I created https://sagebionetworks.jira.com/browse/SYNPY-959 to track the engineering progress. If this issue impact your downstream work (e.g., using the path to access the file), please let us know.

**Comment by pcstout** [comment]
Thanks @kimyen.
This is impacting one of our projects but we have some workarounds. Would be nice to get this fixed sooner than later though.
