### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by fizwit** [Sage-Bionetworks/synapsePythonClient#689]
# Bug Report

## Operating system
Ubuntu 14.04/18.04

## Client version
```
Python 3.7.4
synapseclient 1.9.3
```

## Description of the problem
```
>>> import synapseclient
ImportError: cannot import name 'csv' from 'backports' (/app/easybuild/software/Python/3.7.4-foss-2016b-fh1/lib/python3.7/site-packages/backports/__init__.py)
```
Why use backports with Python 3.x ?

**Comment by zimingd** [comment]
It's odd that the required dependency did not get automatically installed:
`pip install backports.csv`
We're using backports because version 1.9.3 still has Python 2 support.
We will be dropping Python 2 support and removing `backports` for the next version (2.0.0).

**Comment by fizwit** [comment]
I have since installed backports.csv.  Backports was not listed as a
dependency.

John Dey
john@fuzzdog.com
