### ISSUE TITLE
support python 3.8

### ISSUE THREAD

**Issue by joshua-gould** [Sage-Bionetworks/synapsePythonClient#719]
Installation fails using python 3.8 due to check in setup.py

**Comment by keller-mark** [comment]
Where is version 2.0? https://github.com/Sage-Bionetworks/synapsePythonClient/blob/develop/README.md#python-2-support

**Comment by zimingd** [comment]
@keller-mark 
That section in the README is pretty outdated. We forgot to update that when our development priorities switched.

We currently have a release-candidate for 2.0. Looking to release as soon as all issues on JIRA are validated in the next few days.
https://sagebionetworks.jira.com/issues/?jql=project%20%3D%20SYNPY%20AND%20fixVersion%20%3D%20py-2.0%20ORDER%20BY%20cf%5B11140%5D%20ASC

It's on test.pypi if you want to play around with it before we release. 
https://test.pypi.org/project/synapseclient/

**Comment by zimingd** [comment]
closing because v2.0.0 is released
