### ISSUE TITLE
Allow overriding the cache location via Synapse() constructor

### ISSUE THREAD

**Issue by keller-mark** [Sage-Bionetworks/synapsePythonClient#767]
# Bug Report

## Operating system

macOS

## Client version
2.1.0

## Description of the problem

*Provide a description of the problem, and if possible a minimal reproducible example.*

I would like to download one dataset to one directory, and a second dataset to a different directory, but these need to be downloaded using the `syn.downloadTableColumns` function.

This function automatically downloads to the cache location, so this is not possible without updating the config file in between.

It would be great if the cache location could be set in the `Synapse()` constructor directly.

**Comment by jkiang13** [comment]
@keller-mark Thanks for the suggestion. So I understand the general need, you'd like to be able to use `downloadTableColumns` to download to an alternate path than the default cache. Would something like an optional `downloadLocation` parameter on `downloadTableColumns` similar to `syn.get` also satisfy this requirement?

In the meantime, something like the following utility method might be useful as a workaround:

```python
import configparser
import synapseclient
import tempfile


def synapse_custom_cache_dir(cache_dir):
    """Return a new Synapse instance with the given cache directory as its configured cache root"""

    config = configparser.RawConfigParser()
    config.read(synapseclient.client.CONFIG_FILE)

    if not config.has_section('cache'):
        config.add_section('cache')
    config['cache']['location'] = cache_dir

    with tempfile.NamedTemporaryFile(mode='w') as tempconfig:
        config.write(tempconfig)
        tempconfig.flush()

        return synapseclient.Synapse(configPath=tempconfig.name)
```

Sample usage:

```python
syn = synapse_custom_cache_dir('/path/to/location1')
syn.login()
results = syn.tableQuery('SELECT * FROM syn123 LIMIT 5')
syn.downloadTableColumns(results, ['foo', 'bar'])

syn = synapse_custom_cache_dir('/path/to/location2')
syn.login()
results = syn.tableQuery('SELECT * FROM syn456 LIMIT 5')
syn.downloadTableColumns(results, ['foo', 'bar'])
```

**Comment by keller-mark** [comment]
A downloadLocation parameter would be great. Thanks for the workaround.
