### ISSUE TITLE
Connecting to Synapse documentation

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapsePythonClient#778]
## Client version
2.1.1

## Description of the problem

Use of the api key is buried in the reference documentation. Recommend use of api key in [Connecting to Synapse](https://python-docs.synapse.org/build/html/index.html#connecting-to-synapse). Users will first arrive to this location before searching the reference documentation.

**Comment by thomasyu888** [comment]
This will be resolved with the documentation revamp.
