### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by sheenaseven** [Sage-Bionetworks/synapsePythonClient#799]
When I used "source("http://depot.sagebase.org/CRAN.R");pkgInstall("synapseClient")" to install "synapseClient" in my Rstudio, I encountered the attached problem on Timeout. Do you have other install methods? My system is macOS 10.14.6, and my Rstudio is 4.0.3 version.

![image](https://user-images.githubusercontent.com/37868618/104286019-70201600-54ef-11eb-91d3-0c4309927fdd.png)

**Comment by zimingd** [comment]
Hi @sheenaseven ,

This project is for our Python client.
If you wish to install the R client please refer to the instructions at:
https://github.com/Sage-Bionetworks/synapser
