### ISSUE TITLE
utils' `is_synapse_id` does not work as intended

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/synapsePythonClient#947]
# Bug Report

One of our collaborators for a challenge wants to implement a check in their workflow to ensure given IDs are valid Synapse IDs.  I suggested the utils function, `is_synapse_id`, but after looking at the implementation, I think the function needs to be revisited.

## Description of the problem

The current `is_synapse_id` function returns a substring that matches `r"(syn\d+)"`.

### Expected behavior

Honestly, because the function name starts with `is`, I expected a boolean to be returned, not a string.  Maybe we can rewrite the function as this?

```python
>>> def is_synapse_id(syn_id):
...   try:
...     syn.get(syn_id, downloadFile=False)
...   except synapseclient.core.exceptions.SynapseFileNotFoundError:
...     return False
...   except synapseclient.core.exceptions.SynapseHTTPError as err:
...     if err.response.status_code in (400, 404):
...       return False
...     # Valid ID but lacks permission
...     elif err.response.status_code == 403:
...       return True
...   else:
...     return True
... 
>>> is_synapse_id("test")
False
>>> is_synapse_id("123")
False
>>> is_synapse_id("syn123")
False
>>> is_synapse_id("syn123abc")
False
>>> is_synapse_id("syn28590455")
True
>>> is_synapse_id("syn22392179")
True
```

### Actual behavior

As noted above, any strings that begin with `syn` followed by numbers will be returned.  This will include strings that have letters that follow the digits and IDs that are actually not valid synIDs.

```python
>>> from synapseclient.core import utils
>>> utils.is_synapse_id("test")
>>> utils.is_synapse_id("123")
>>> utils.is_synapse_id("syn123")
'syn123'
>>> utils.is_synapse_id("syn123abc")
'syn123'
>>> utils.is_synapse_id("syn28590455")
'syn28590455'
>>> utils.is_synapse_id("syn22392179")
'syn22392179'
```

**Comment by vpchung** [comment]
^ on second thought, maybe we shouldn't use the `else` above, in case another exception arises.

**Comment by vpchung** [comment]
After doing a couple more tests, I think this function is ✨the one✨ 

```python
>>> def is_synapse_id(syn_id):
...   try:
...     try:
...       syn.get(syn_id, downloadFile=False)
...     except synapseclient.core.exceptions.SynapseFileNotFoundError:
...       return False
...     except synapseclient.core.exceptions.SynapseHTTPError as err:
...       if err.response.status_code in (400, 404):
...         return False
...       # Valid ID but user lacks permission
...       elif err.response.status_code == 403:
...         return True
...   except synapseclient.core.exceptions.SynapseAuthenticationError as err:
...     # Valid ID but user is not logged in
...     if err.__context__.response.status_code == 403:
...       return True
...   return True
... 
>>> 
>>> ### Invalid IDs
>>> is_synapse_id("test")
False
>>> is_synapse_id("123")
False
>>> is_synapse_id("syn123")
False
>>> is_synapse_id("syn123abc")
False
>>> 
>>> ### Valid IDs
>>> is_synapse_id("syn28590455")
True
>>> # ... even when user is not logged in
>>> syn.logout()
>>> is_synapse_id("syn36025126")
True
>>> syn.login(silent=True)
>>> is_synapse_id("syn36025126")
True
>>> # ... even when user lacks access
>>> is_synapse_id("syn22392179")
True
```

**Comment by thomasyu888** [comment]
Thanks for the implementation details. @vpchung  I really like but some comments.

The above implementation is tied to a synapse connection which would "complicate" the utils function to require a synapse login to do this.  I think the utility function could be better named like
"Is_synapse_id_str".  I think implementation above could be contributed as a client function!

**Comment by vpchung** [comment]
Yeah, after trying to implement it into `utils`, I realize why it was written the way it was 😅 I do have a regex suggestion though!

> could be contributed as a client function!

Will do a PR for it!
