### ISSUE TITLE
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by NarayanSchuetz** [Sage-Bionetworks/synapsePythonClient#957]
# Bug Report
Importing Synapseclient on Linux system causes an import Error if LibreSSL is used instead of OpenSSL.

## Operating system
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

## Client version
Python 3.9.0
Synapse 2.7.0

## Description of the problem
Importing Synapseclient on Linux system causes an import Error if LibreSSL is used instead of OpenSSL.
Can be hotfixed by installing an older version of `urllib3`, but that is not the ideal solution going forward, I'd assume.

### Expected behavior

No error ;)

### Actual behavior
```
.local/lib/python3.9/site-packages/synapseclient/__init__.py:275: in <module>
    from .activity import Activity
.local/lib/python3.9/site-packages/synapseclient/activity.py:74: in <module>
    from synapseclient.core.exceptions import SynapseError, SynapseMalformedEntityError
.local/lib/python3.9/site-packages/synapseclient/core/exceptions.py:15: in <module>
    import requests
.local/lib/python3.9/site-packages/requests/__init__.py:43: in <module>
    import urllib3
.local/lib/python3.9/site-packages/urllib3/__init__.py:38: in <module>
    raise ImportError(
E   ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 3.2.1. See: https://github.com/urllib3/urllib3/issues/2168
```

**Comment by NarayanSchuetz** [comment]
Can be hotfixed by downgrading urllib3:

    pip3 install "urllib3 <=1.26.15"

**Comment by thomasyu888** [comment]
Thanks for pointing this out @NarayanSchuetz . I will make a patch release soon.

**Comment by thomasyu888** [comment]
After looking more into this @NarayanSchuetz , may I ask why you are using `LibreSSL` over `OpenSSL`? 

Python is going to require OpenSSL with PEP 644 and dropping support for Python with an `ssl` module compiled with LibreSSL, CiscoSSL, wolfSSL, and all other OpenSSL alternatives.

That said, its still going to be awhile before python 3.8 and 3.9 are EOL, so I still think it may be worth it to do do a `urllib3<2` patch.

**Comment by NarayanSchuetz** [comment]
Our HPC env here at Stanford comes with `LibreSSL` unfortunately...

**Comment by thomasyu888** [comment]
Thanks for reporting this @NarayanSchuetz .  2.7.2 should be released very soon with this patch.
