### ISSUE TITLE
[Bug] unexpected keyword argument 'line_terminator'

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/synapsePythonClient#977]
# Bug Report

## Operating system

Mac

## Client version

2.7.2

(I believe it's an issue with `pandas` though, not the client)

## Description of the problem

When attempting to store a table, the following error is received:

```python
...
  File "/Users/vchung/opt/miniconda3/envs/synapse/lib/python3.10/site-packages/synapseclient/table.py", line 1655, in Table
    return CsvFileTable.from_data_frame(schema, values, **kwargs)
  File "/Users/vchung/opt/miniconda3/envs/synapse/lib/python3.10/site-packages/synapseclient/table.py", line 2063, in from_data_frame
    df.to_csv(f,
TypeError: NDFrame.to_csv() got an unexpected keyword argument 'line_terminator'
```

### Expected behavior

`syn.store(Table(synID, df))` should work and the Synapse table would be updated.

### Actual behavior

The error pasted above is received.

Note: this is only seen with pandas >=2.0.0

**Comment by vpchung** [comment]
Whoops, I just realized that [a fix](https://github.com/Sage-Bionetworks/synapsePythonClient/commit/53c8b0b64ad6ae93b4ebab26ad67cb1eb1389528) is already in the works in the `develop` branch.

Closing this bug report~

**Comment by thomasyu888** [comment]
@vpchung for the most recent client release. Pandas version is tied to <1.5.

That will resolve your issue.
